spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: phumlanidev
    password: Chr1st1@n9432

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 7000
application:
  security:
    jwt:
      expiration: 86400000
      secret-key: 4E645267556B58703273357638792F423F4428472B4B6250655368566D59713
      refresh-token:
        expiration: 604800000